kind: pipeline
type: docker
name: checker

steps:
  - name: node-modules
    image: node:13
    commands:
      - npm ci
  - name: eslint
    image: node:13
    commands:
      - npm run eslint
      - npm run validate-configs

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: latest-test

steps:
  - name: node-modules
    image: node:13
    commands:
      - npm ci
  - name: test-run-latest
    image: node:13
    commands:
      - npm run start -- build

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: latest-krankerl-enabled-test

steps:
  - name: node-modules
    image: node:13
    commands:
      - npm ci
  - name: test-run-latest
    image: node:13
    commands:
      - npm run start -- build --exec-krankerl-cmds true

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: nc-18.0.2-test

steps:
  - name: node-modules
    image: node:13
    commands:
      - npm ci
  - name: test-run-latest
    image: node:13
    commands:
      - npm run start -- build --nc-version v18.0.2

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: nc-17.0.5-test

steps:
  - name: node-modules
    image: node:13
    commands:
      - npm ci
  - name: test-run-latest
    image: node:13
    commands:
      - npm run start -- build --nc-version v17.0.5

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
